export const ELEMENTS = [
  {symbol:'H',  name:'Hydrogen',   color:0xffffff, density:0.07,  state:'gas',  radio:false, decay:null,  price:0  },
  {symbol:'He', name:'Helium',     color:0x87ceeb, density:0.16,  state:'gas',  radio:false, decay:null,  price:10 },
  {symbol:'Li', name:'Lithium',    color:0xb8860b, density:0.53,  state:'solid',radio:false, decay:null,  price:20 },
  {symbol:'Be', name:'Beryllium',  color:0xc0c0c0, density:1.85,  state:'solid',radio:false, decay:null,  price:100},
  {symbol:'B',  name:'Boron',      color:0xffd700, density:2.34,  state:'solid',radio:false, decay:null,  price:50 },
  {symbol:'C',  name:'Carbon',     color:0x2f4f4f, density:2.27,  state:'solid',radio:false, decay:null,  price:10 },
  {symbol:'N',  name:'Nitrogen',   color:0x87cefa, density:0.81,  state:'gas',  radio:false, decay:null,  price:10 },
  {symbol:'O',  name:'Oxygen',     color:0xff0000, density:1.14,  state:'gas',  radio:false, decay:null,  price:10 },
  {symbol:'F',  name:'Fluorine',   color:0x00ffff, density:1.33,  state:'gas',  radio:false, decay:null,  price:200},
  {symbol:'Ne', name:'Neon',       color:0xffb6c1, density:0.90,  state:'gas',  radio:false, decay:null,  price:50 },
  {symbol:'Na', name:'Sodium',     color:0x1e90ff, density:0.97,  state:'solid',radio:false, decay:null,  price:30 },
  {symbol:'Mg', name:'Magnesium',  color:0xdeb887, density:1.74,  state:'solid',radio:false, decay:null,  price:40 },
  {symbol:'Al', name:'Aluminum',   color:0xc0c0c0, density:2.70,  state:'solid',radio:false, decay:null,  price:30 },
  {symbol:'Si', name:'Silicon',    color:0xdaa520, density:2.33,  state:'solid',radio:false, decay:null,  price:25 },
  {symbol:'P',  name:'Phosphorus', color:0xffa500, density:1.82,  state:'solid',radio:false, decay:null,  price:80 },
  {symbol:'S',  name:'Sulfur',     color:0xffff00, density:2.07,  state:'solid',radio:false, decay:null,  price:30 },
  {symbol:'Cl', name:'Chlorine',   color:0x00ff00, density:2.99,  state:'gas',  radio:false, decay:null,  price:40 },
  {symbol:'Ar', name:'Argon',      color:0xff69b4, density:1.78,  state:'gas',  radio:false, decay:null,  price:60 },
  {symbol:'K',  name:'Potassium',  color:0x4169e1, density:0.86,  state:'solid',radio:false, decay:null,  price:50 },
  {symbol:'Ca', name:'Calcium',    color:0x708090, density:1.55,  state:'solid',radio:false, decay:null,  price:40 },
  {symbol:'Sc', name:'Scandium',   color:0x87ceeb, density:2.99,  state:'solid',radio:false, decay:null,  price:300},
  {symbol:'Ti', name:'Titanium',   color:0x7fffd4, density:4.51,  state:'solid',radio:false, decay:null,  price:100},
  {symbol:'V',  name:'Vanadium',   color:0x6495ed, density:6.11,  state:'solid',radio:false, decay:null,  price:200},
  {symbol:'Cr', name:'Chromium',   color:0xf5deb3, density:7.19,  state:'solid',radio:false, decay:null,  price:120},
  {symbol:'Mn', name:'Manganese',  color:0xffa07a, density:7.21,  state:'solid',radio:false, decay:null,  price:150},
  {symbol:'Fe', name:'Iron',       color:0xd3d3d3, density:7.87,  state:'solid',radio:false, decay:null,  price:20 },
  {symbol:'Co', name:'Cobalt',     color:0x4682b4, density:8.90,  state:'solid',radio:false, decay:null,  price:200},
  {symbol:'Ni', name:'Nickel',     color:0xd2691e, density:8.91,  state:'solid',radio:false, decay:null,  price:50 },
  {symbol:'Cu', name:'Copper',     color:0xcd853f, density:8.96,  state:'solid',radio:false, decay:null,  price:40 },
  {symbol:'Zn', name:'Zinc',       color:0xf0e68c, density:7.14,  state:'solid',radio:false, decay:null,  price:30 },
  {symbol:'Ga', name:'Gallium',    color:0xdc143c, density:5.91,  state:'solid',radio:false, decay:null,  price:400},
  {symbol:'Ge', name:'Germanium',  color:0x20b2aa, density:5.32,  state:'solid',radio:false, decay:null,  price:300},
  {symbol:'As', name:'Arsenic',    color:0x9370db, density:5.72,  state:'solid',radio:false, decay:null,  price:150},
  {symbol:'Se', name:'Selenium',   color:0x3cb371, density:4.82,  state:'solid',radio:false, decay:null,  price:250},
  {symbol:'Br', name:'Bromine',    color:0x8b0000, density:3.12,  state:'liquid',radio:false, decay:null, price:300},
  {symbol:'Kr', name:'Krypton',    color:0xff6347, density:3.75,  state:'gas',  radio:false, decay:null,  price:400},
  {symbol:'Rb', name:'Rubidium',   color:0x483d8b, density:1.53,  state:'solid',radio:false, decay:null,  price:500},
  {symbol:'Sr', name:'Strontium',  color:0x2e8b57, density:2.63,  state:'solid',radio:false, decay:null,  price:300},
  {symbol:'Y',  name:'Yttrium',    color:0x556b2f, density:4.47,  state:'solid',radio:false, decay:null,  price:400},
  {symbol:'Zr', name:'Zirconium',  color:0x00fa9a, density:6.51,  state:'solid',radio:false, decay:null,  price:250},
  {symbol:'Nb', name:'Niobium',    color:0x008b8b, density:8.57,  state:'solid',radio:false, decay:null,  price:350},
  {symbol:'Mo', name:'Molybdenum', color:0x696969, density:10.28, state:'solid',radio:false, decay:null,  price:300},
  {symbol:'Tc', name:'Technetium', color:0x2f4f4f, density:11.5,  state:'solid',radio:true,  decay:null,  price:1000},
  {symbol:'Ru', name:'Ruthenium',  color:0x4b0082, density:12.37, state:'solid',radio:false, decay:null,  price:500},
  {symbol:'Rh', name:'Rhodium',    color:0x48d1cc, density:12.45, state:'solid',radio:false, decay:null,  price:800},
  {symbol:'Pd', name:'Palladium',  color:0xafeeee, density:12.02, state:'solid',radio:false, decay:null,  price:700},
  {symbol:'Ag', name:'Silver',     color:0xc0c0c0, density:10.49, state:'solid',radio:false, decay:null,  price:100},
  {symbol:'Cd', name:'Cadmium',    color:0x9400d3, density:8.65,  state:'solid',radio:false, decay:null,  price:200},
  {symbol:'In', name:'Indium',     color:0x000080, density:7.31,  state:'solid',radio:false, decay:null,  price:300},
  {symbol:'Sn', name:'Tin',        color:0x66cdaa, density:7.31,  state:'solid',radio:false, decay:null,  price:80 },
  {symbol:'Sb', name:'Antimony',   color:0x483d8b, density:6.69,  state:'solid',radio:false, decay:null,  price:150},
  {symbol:'Te', name:'Tellurium',  color:0x556b2f, density:6.24,  state:'solid',radio:false, decay:null,  price:400},
  {symbol:'I',  name:'Iodine',     color:0x9932cc, density:4.93,  state:'solid',radio:false, decay:null,  price:200},
  {symbol:'Xe', name:'Xenon',      color:0xff1493, density:5.90,  state:'gas',  radio:false, decay:null,  price:500},
  {symbol:'Cs', name:'Cesium',     color:0x191970, density:1.93,  state:'solid',radio:false, decay:null,  price:600},
  {symbol:'Ba', name:'Barium',     color:0x0000cd, density:3.51,  state:'solid',radio:false, decay:null,  price:300},
  {symbol:'La', name:'Lanthanum',  color:0x00ced1, density:6.15,  state:'solid',radio:false, decay:null,  price:400},
  {symbol:'Ce', name:'Cerium',     color:0x9400d3, density:6.77,  state:'solid',radio:false, decay:null,  price:350},
  {symbol:'Pr', name:'Praseodymium', color:0x00008b, density:6.77, state:'solid',radio:false, decay:null, price:500},
  {symbol:'Nd', name:'Neodymium',  color:0x1e90ff, density:7.01,  state:'solid',radio:false, decay:null,  price:300},
  {symbol:'Pm', name:'Promethium', color:0x708090, density:7.26,  state:'solid',radio:true,  decay:null,  price:1000},
  {symbol:'Sm', name:'Samarium',   color:0x4169e1, density:7.52,  state:'solid',radio:false, decay:null,  price:400},
  {symbol:'Eu', name:'Europium',   color:0xdb7093, density:5.24,  state:'solid',radio:false, decay:null,  price:600},
  {symbol:'Gd', name:'Gadolinium', color:0x5f9ea0, density:7.90,  state:'solid',radio:false, decay:null,  price:500},
  {symbol:'Tb', name:'Terbium',    color:0x4682b4, density:8.23,  state:'solid',radio:false, decay:null,  price:700},
  {symbol:'Dy', name:'Dysprosium', color:0x008080, density:8.55,  state:'solid',radio:false, decay:null,  price:600},
  {symbol:'Ho', name:'Holmium',    color:0x00ff7f, density:8.80,  state:'solid',radio:false, decay:null,  price:700},
  {symbol:'Er', name:'Erbium',     color:0x0000ff, density:9.07,  state:'solid',radio:false, decay:null,  price:650},
  {symbol:'Tm', name:'Thulium',    color:0x7cfc00, density:9.32,  state:'solid',radio:false, decay:null,  price:800},
  {symbol:'Yb', name:'Ytterbium',  color:0xff00ff, density:6.90,  state:'solid',radio:false, decay:null,  price:700},
  {symbol:'Lu', name:'Lutetium',   color:0x00ffff, density:9.84,  state:'solid',radio:false, decay:null,  price:900},
  {symbol:'Hf', name:'Hafnium',    color:0x8a2be2, density:13.31, state:'solid',radio:false, decay:null,  price:500},
  {symbol:'Ta', name:'Tantalum',   color:0x32cd32, density:16.65, state:'solid',radio:false, decay:null,  price:600},
  {symbol:'W',  name:'Tungsten',   color:0x7b68ee, density:19.25, state:'solid',radio:false, decay:null,  price:400},
  {symbol:'Re', name:'Rhenium',    color:0x4169e1, density:21.02, state:'solid',radio:false, decay:null,  price:800},
  {symbol:'Os', name:'Osmium',     color:0x20b2aa, density:22.59, state:'solid',radio:false, decay:null,  price:900},
  {symbol:'Ir', name:'Iridium',    color:0x00fa9a, density:22.56, state:'solid',radio:false, decay:null,  price:1000},
  {symbol:'Pt', name:'Platinum',   color:0xb0c4de, density:21.45, state:'solid',radio:false, decay:null,  price:800},
  {symbol:'Au', name:'Gold',       color:0xffd700, density:19.32, state:'solid',radio:false, decay:null,  price:500},
  {symbol:'Hg', name:'Mercury',    color:0xc0c0c0, density:13.53, state:'liquid',radio:false, decay:null, price:600},
  {symbol:'Tl', name:'Thallium',   color:0x808000, density:11.85, state:'solid',radio:false, decay:null,  price:400},
  {symbol:'Pb', name:'Lead',       color:0xa9a9a9, density:11.34, state:'solid',radio:false, decay:null,  price:200},
  {symbol:'Bi', name:'Bismuth',    color:0x7fffd4, density:9.78,  state:'solid',radio:false, decay:null,  price:300},
  {symbol:'Po', name:'Polonium',   color:0x2e8b57, density:9.20,  state:'solid',radio:true,  decay:'Pb',  price:1500},
  {symbol:'At', name:'Astatine',   color:0x483d8b, density:8.97,  state:'solid',radio:true,  decay:'Bi',  price:2000},
  {symbol:'Rn', name:'Radon',      color:0xff0000, density:9.73,  state:'gas',  radio:true,  decay:'Po',  price:1000},
  {symbol:'Fr', name:'Francium',   color:0x191970, density:1.87,  state:'solid',radio:true,  decay:'Ra',  price:2500},
  {symbol:'Ra', name:'Radium',     color:0x000080, density:5.50,  state:'solid',radio:true,  decay:'Rn',  price:2000},
  {symbol:'Ac', name:'Actinium',   color:0x8b008b, density:10.07, state:'solid',radio:true,  decay:'Th',  price:2500},
  {symbol:'Th', name:'Thorium',    color:0x2f4f4f, density:11.72, state:'solid',radio:true,  decay:'Pa',  price:1800},
  {symbol:'Pa', name:'Protactinium', color:0x4682b4, density:15.37, state:'solid',radio:true, decay:'U',   price:2500},
  {symbol:'U',  name:'Uranium',    color:0x006400, density:19.05, state:'solid',radio:true,  decay:'Th',  price:1500},
  {symbol:'Np', name:'Neptunium',  color:0x800000, density:20.48, state:'solid',radio:true,  decay:'Pu',  price:3000},
  {symbol:'Pu', name:'Plutonium',  color:0x4b0082, density:19.82, state:'solid',radio:true,  decay:'U',   price:3000},
  {symbol:'Am', name:'Americium',  color:0x8b0000, density:13.67, state:'solid',radio:true,  decay:'Np',  price:3500},
  {symbol:'Cm', name:'Curium',     color:0x00008b, density:13.51, state:'solid',radio:true,  decay:'Pu',  price:4000},
  {symbol:'Bk', name:'Berkelium',  color:0x9932cc, density:14.78, state:'solid',radio:true,  decay:'Cf',  price:4500},
  {symbol:'Cf', name:'Californium', color:0x483d8b, density:15.10, state:'solid',radio:true, decay:'Cm',  price:5000},
  {symbol:'Es', name:'Einsteinium', color:0x2e8b57, density:8.84,  state:'solid',radio:true,  decay:'Bk',  price:5500},
  {symbol:'Fm', name:'Fermium',    color:0x008080, density:9.71,  state:'solid',radio:true,  decay:'Es',  price:6000},
  {symbol:'Md', name:'Mendelevium', color:0x708090, density:10.3,  state:'solid',radio:true,  decay:'Fm',  price:6500},
  {symbol:'No', name:'Nobelium',   color:0x4169e1, density:9.94,  state:'solid',radio:true,  decay:'Md',  price:7000},
  {symbol:'Lr', name:'Lawrencium', color:0x8a2be2, density:15.6,  state:'solid',radio:true,  decay:'No',  price:7500},
  {symbol:'Rf', name:'Rutherfordium', color:0xdb7093, density:23.2, state:'solid',radio:true,  decay:'Db',  price:8000},
  {symbol:'Db', name:'Dubnium',    color:0x48d1cc, density:29.3,  state:'solid',radio:true,  decay:'Sg',  price:8500},
  {symbol:'Sg', name:'Seaborgium', color:0xafEEEE, density:35.0,  state:'solid',radio:true,  decay:'Bh',  price:9000},
  {symbol:'Bh', name:'Bohrium',    color:0x7fffd4, density:37.1,  state:'solid',radio:true,  decay:'Hs',  price:9500},
  {symbol:'Hs', name:'Hassium',    color:0x00fa9a, density:40.7,  state:'solid',radio:true,  decay:'Mt',  price:10000},
  {symbol:'Mt', name:'Meitnerium', color:0x4169e1, density:37.4,  state:'solid',radio:true,  decay:'Ds',  price:11000},
  {symbol:'Ds', name:'Darmstadtium', color:0x0000cd, density:34.8, state:'solid',radio:true,  decay:'Rg',  price:12000},
  {symbol:'Rg', name:'Roentgenium', color:0x9400d3, density:28.7, state:'solid',radio:true,  decay:'Cn',  price:13000},
  {symbol:'Cn', name:'Copernicium', color:0xff6347, density:23.7, state:'solid',radio:true,  decay:'Nh',  price:14000},
  {symbol:'Nh', name:'Nihonium',   color:0x7cfc00, density:16.0,  state:'solid',radio:true,  decay:'Fl',  price:15000},
  {symbol:'Fl', name:'Flerovium',  color:0x00ff7f, density:14.0,  state:'solid',radio:true,  decay:'Mc',  price:16000},
  {symbol:'Mc', name:'Moscovium',  color:0x0000ff, density:13.5,  state:'solid',radio:true,  decay:'Lv',  price:17000},
  {symbol:'Lv', name:'Livermorium', color:0xff00ff, density:12.9, state:'solid',radio:true,  decay:'Ts',  price:18000},
  {symbol:'Ts', name:'Tennessine', color:0xffff00, density:7.2,   state:'solid',radio:true,  decay:'Og',  price:19000},
  {symbol:'Og', name:'Oganesson',  color:0xdda0dd, density:7.2,   state:'solid',radio:true,  decay:'Lv',  price:20000}
];
export const SYM2ID = Object.fromEntries(ELEMENTS.map((e,i)=>[e.symbol,i]));
export const ID2SYM = ELEMENTS.map(e=>e.symbol);